# Site
name: 'HPKU'
description: 'HPku - informasi seputar gadget '
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url: "https://hpku.info"
baseurl: ''
disqus: 'hpkuinfo'
email: 'emmamery93@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: [""]
  endings: [all]
  profile: false
  blanklines: false
  ignore:
    envs: []
    
authors:
    Mery:
      name:           Mery 
      site:           https://hpku.info
      avatar:         /assets/images/avatar1.png
      bio:            "Hi, I am Emma, the author of Hpku.info, Blog seputar smartphone "
      email:          emmamery93@gmail.com 
 
    
authors:
    Mery:
      name:           Mery
      site:           https://iinewstech.com/
      avatar:         /assets/images/avatar1.png
      bio:            "Hi selamat datang di web aku ya, semoga betah :) "
      email:          emmamery93@gmail.com 
      twitter:        https://twitter.com
      facebook:       https://facebook.com/mmomery
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Mery
      avatar: /assets/images/avatar1.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Paginate
paginate_path: /page/:num/
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
