# Site
name: 'HPKU'
description: 'HPku - informasi seputar gadget '
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url: "https://hpku.info"
baseurl: ''
disqus: 'hpkuinfo'
email: 'ytube1897@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title.html

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Anto:
      name:           Mery 
      site:           https://hpku.info
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Emma, the author of Hpku.info, Blog seputar smartphone "
      email:          emmamery93@gmail.com 
      
    Mery:
      name:           Mery 
      site:           https://hpku.info
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Emma, the author of Hpku.info, Blog seputar smartphone "
      email:          emmamery93@gmail.com 
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: anto
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
include: [_redirect]
